In [57]:
from sklearn import metrics
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [58]:
dataset = pd.read_csv("roo_data.csv")

In [59]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype 
---  ------                                    --------------  ----- 
 0   Acedamic percentage in Operating Systems  20000 non-null  int64 
 1   percentage in Algorithms                  20000 non-null  int64 
 2   Percentage in Programming Concepts        20000 non-null  int64 
 3   Percentage in Software Engineering        20000 non-null  int64 
 4   Percentage in Computer Networks           20000 non-null  int64 
 5   Percentage in Electronics Subjects        20000 non-null  int64 
 6   Percentage in Computer Architecture       20000 non-null  int64 
 7   Percentage in Mathematics                 20000 non-null  int64 
 8   Percentage in Communication skills        20000 non-null  int64 
 9   Hours working per day                     20000 non-null  int64 
 10  Logical quotient rating                   2000

In [60]:
dataset.describe()

Acedamic percentage in Operating Systems  ...  public speaking points
count                              20000.000000  ...            20000.000000
mean                                  77.002300  ...                5.012800
std                                   10.085697  ...                2.588875
min                                   60.000000  ...                1.000000
25%                                   68.000000  ...                3.000000
50%                                   77.000000  ...                5.000000
75%                                   86.000000  ...                7.000000
max                                   94.000000  ...                9.000000

[8 rows x 14 columns]

In [61]:
drop_columns = ['Hours working per day','Management or Technical','hackathons','can work long time before system?','Extra-courses did','workshops','worked in teams ever?','self-learning capability?','memory capability score','Job/Higher Studies?','hard/smart worker','talenttests taken?','olympiads','reading and writing skills','Type of company want to settle in?','interested in games','Taken inputs from seniors or elders','Interested Type of Books','In a Realtionship?','Gentle or Tuff behaviour?','Introvert']
final = dataset.drop(drop_columns, axis = 1)

In [62]:
final.head()

Acedamic percentage in Operating Systems  ...              Suggested Job Role
0                                        69  ...              Database Developer
1                                        78  ...            Portal Administrator
2                                        71  ...            Portal Administrator
3                                        76  ...  Systems Security Administrator
4                                        92  ...        Business Systems Analyst

[5 rows x 18 columns]

In [63]:
df = final.iloc[:,:9]

In [64]:
df.head()

Acedamic percentage in Operating Systems  ...  Percentage in Communication skills
0                                        69  ...                                  61
1                                        78  ...                                  91
2                                        71  ...                                  94
3                                        76  ...                                  69
4                                        92  ...                                  73

[5 rows x 9 columns]

In [65]:
df['Average Academic Percentage'] = df.mean(axis=1)

In [66]:
df.head()

Acedamic percentage in Operating Systems  ...  Average Academic Percentage
0                                        69  ...                    79.666667
1                                        78  ...                    73.555556
2                                        71  ...                    79.444444
3                                        76  ...                    76.444444
4                                        92  ...                    76.444444

[5 rows x 10 columns]

In [67]:
drop_list = ['Acedamic percentage in Operating Systems',	'percentage in Algorithms'	,'Percentage in Programming Concepts','Percentage in Software Engineering',	'Percentage in Computer Networks',	'Percentage in Electronics Subjects'	,'Percentage in Computer Architecture',	'Percentage in Mathematics',	'Percentage in Communication skills']

In [68]:
df1 = df.drop(drop_list, axis = 1)

In [69]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 1 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Average Academic Percentage  20000 non-null  float64
dtypes: float64(1)
memory usage: 156.4 KB


In [70]:
df1.head()

Average Academic Percentage
0                    79.666667
1                    73.555556
2                    79.444444
3                    76.444444
4                    76.444444

In [71]:
df2 = df1['Average Academic Percentage'].nunique()
df2

205

In [72]:
df3 = final.iloc[:,9:]

In [73]:
df3.head()

Logical quotient rating  ...              Suggested Job Role
0                        4  ...              Database Developer
1                        7  ...            Portal Administrator
2                        1  ...            Portal Administrator
3                        1  ...  Systems Security Administrator
4                        5  ...        Business Systems Analyst

[5 rows x 9 columns]

In [74]:
final_df = pd.concat([df1,df3],axis=1)

In [75]:
final_df.head()

Average Academic Percentage  ...              Suggested Job Role
0                    79.666667  ...              Database Developer
1                    73.555556  ...            Portal Administrator
2                    79.444444  ...            Portal Administrator
3                    76.444444  ...  Systems Security Administrator
4                    76.444444  ...        Business Systems Analyst

[5 rows x 10 columns]

In [76]:
final_df.shape

(20000, 10)

In [77]:
Suggested_DF = final_df.iloc[:,9:]

In [78]:
Suggested_DF.head()

Suggested Job Role
0              Database Developer
1            Portal Administrator
2            Portal Administrator
3  Systems Security Administrator
4        Business Systems Analyst

In [79]:
Suggested_DF['Suggested Job Role'].replace({"Database Developer": 'Database Profile','Database Manager':'Database Profile','Database Administrator':'Database Profile','Data Architect': "Database Profile", 'Technical Support':'Technical/Support Profile','Technical Services/Help Desk/Tech Support':'Technical/Support Profile','Information Technology Auditor':'Technical/Support Profile','Software Quality Assurance (QA) / Testing':'Technical/Support Profile','Information Technology Manager':'Technical/Support Profile','Technical Engineer':'Technical/Support Profile','Portal Administrator':'Technical/Support Profile','Quality Assurance Associate':'Technical/Support Profile','Systems Analyst':'Technical/Support Profile','Solutions Architect':'Technical/Support Profile','Systems Security Administrator':'Networking Profile','Network Security Administrator':'Networking Profile','Network Engineer':'Networking Profile','Network Security Engineer':'Networking Profile','Information Security Analyst':'Networking Profile','UX Designer':'Design Profile','Design & UX':'Design Profile',"Business Systems Analyst": "Business Profile", "Business Intelligence Analyst": "Business Profile", "Project Manager":"Business Profile","E-Commerce Analyst": "Business Profile","CRM Technical Developer": 'Technical/Support Profile', "CRM Business Analyst": "Business Profile","Software Systems Engineer": "Software Profile",'Programmer Analyst':'Software Profile',"Mobile Applications Developer": "Software Profile", "Web Developer": "Software Profile", "Software Developer": "Software Profile", "Applications Developer": "Software Profile", "Software Engineer": "Software Profile"}, inplace=True)

In [80]:
Suggested_DF.head()

Suggested Job Role
0           Database Profile
1  Technical/Support Profile
2  Technical/Support Profile
3         Networking Profile
4           Business Profile

In [81]:
Suggested_DF['Suggested Job Role'].nunique()

6

In [82]:
first_half=final_df.iloc[:,:9]

In [83]:
first_half.head()

Average Academic Percentage  ...  Salary/work
0                    79.666667  ...       salary
1                    73.555556  ...       salary
2                    79.444444  ...         work
3                    76.444444  ...         work
4                    76.444444  ...         work

[5 rows x 9 columns]

In [84]:
roo_datset = pd.concat([first_half,Suggested_DF], axis=1)

In [85]:
roo_datset.shape

(20000, 10)

In [86]:
data = roo_datset.iloc[:,:-1].values
label = roo_datset.iloc[:,-1].values
len(data[0])

9

In [87]:
roo_datset.iloc[:,4:9]

certifications  ... Salary/work
0         shell programming  ...      salary
1          machine learning  ...      salary
2           app development  ...        work
3                    python  ...        work
4           app development  ...        work
...                     ...  ...         ...
19995       app development  ...      salary
19996            full stack  ...      salary
19997  information security  ...        work
19998            full stack  ...        work
19999       app development  ...        work

[20000 rows x 5 columns]

In [88]:
roo_datset.iloc[:,:4]

Average Academic Percentage  ...  public speaking points
0                        79.666667  ...                       8
1                        73.555556  ...                       3
2                        79.444444  ...                       3
3                        76.444444  ...                       5
4                        76.444444  ...                       3
...                            ...  ...                     ...
19995                    74.777778  ...                       8
19996                    76.888889  ...                       8
19997                    80.000000  ...                       3
19998                    75.888889  ...                       5
19999                    77.555556  ...                       6

[20000 rows x 4 columns]

In [89]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [90]:
labelencoder = LabelEncoder()

In [91]:
for i in range(4,9):
    data[:,i] = labelencoder.fit_transform(data[:,i])
data[:5]

array([[79.66666666666667, 4, 4, 8, 8, 4, 4, 1, 0],
       [73.55555555555556, 7, 2, 3, 5, 7, 0, 1, 0],
       [79.44444444444444, 1, 1, 3, 0, 6, 2, 0, 1],
       [76.44444444444444, 1, 2, 5, 6, 7, 5, 0, 1],
       [76.44444444444444, 5, 6, 3, 0, 0, 5, 1, 1]], dtype=object)

In [92]:
data[:5,4:]

array([[8, 4, 4, 1, 0],
       [5, 7, 0, 1, 0],
       [0, 6, 2, 0, 1],
       [6, 7, 5, 0, 1],
       [0, 0, 5, 1, 1]], dtype=object)

In [93]:
from sklearn.preprocessing import Normalizer

In [94]:
data1=data[:,:4]

In [95]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 4)


In [96]:
normalized_data

array([[0.99252184, 0.04983373, 0.04983373, 0.09966746],
       [0.99431909, 0.09462553, 0.02703587, 0.0405538 ],
       [0.9991297 , 0.01257646, 0.01257646, 0.03772937],
       ...,
       [0.99828567, 0.03743571, 0.02495714, 0.03743571],
       [0.99083786, 0.01305643, 0.11750786, 0.06528214],
       [0.99227644, 0.03838319, 0.08956077, 0.07676637]])

In [97]:
data2=data[:,4:]
data2.shape

(20000, 5)

In [98]:
df11 = np.append(normalized_data,data2,axis=1)

df11.shape

(20000, 9)

In [99]:
X1 = pd.DataFrame(df11,columns=['Average Academic Percentage','Logical quotient rating','coding skills rating','public speaking points','certifications','Interested subjects',	'interested career area','Salary Range Expected',	'Salary/work'])

In [100]:
X1.head()

Average Academic Percentage  ... Salary/work
0                    0.992522  ...           0
1                    0.994319  ...           0
2                     0.99913  ...           1
3                    0.997443  ...           1
4                    0.994064  ...           1

[5 rows x 9 columns]

In [101]:
label = labelencoder.fit_transform(label)
print(len(label))

20000


In [102]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()

Suggested Job Role
0                   1
1                   5
2                   5
3                   3
4                   0

In [103]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [145]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,stratify=y,random_state=10)

MLP Classifier

In [146]:
#Importing MLPClassifier
from sklearn.neural_network import MLPClassifier

#Initializing the MLPClassifier
classifier = MLPClassifier(hidden_layer_sizes=(40,10,2), max_iter=300,activation = 'relu',solver='adam',random_state=1)

In [147]:
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(hidden_layer_sizes=(40, 10, 2), max_iter=300, random_state=1)

In [148]:
#Predicting y for X_val
y_pred = classifier.predict(X_test)

In [149]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [150]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[   0    0    0    0    0  571]
 [   0    0    0    0    0  461]
 [   0    0    0    0    0  235]
 [   0    0    0    0    0  694]
 [   0    0    0    0    0  788]
 [   0    0    0    0    0 1251]]
  
accuracy= 31.275


In [151]:
from sklearn.metrics import classification_report

In [152]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       571
           1       0.00      0.00      0.00       461
           2       0.00      0.00      0.00       235
           3       0.00      0.00      0.00       694
           4       0.00      0.00      0.00       788
           5       0.31      1.00      0.48      1251

    accuracy                           0.31      4000
   macro avg       0.05      0.17      0.08      4000
weighted avg       0.10      0.31      0.15      4000



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
